"""Add RegistroAuditoria model

Revision ID: a0e1f2b3c4d5
Revises: faf81b43bfce
Create Date: 2026-08-02 20:36:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0e1f2b3c4d5'
down_revision: Union[str, None] = 'faf81b43bfce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_auditoria_fecha_hora'), 'registros_auditoria', ['fecha_hora'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registros_auditoria_fecha_hora'), table_name='registros_auditoria')
    op.drop_table('registros_auditoria')
    # ### end Alembic commands ###
