"""Initial migration

Revision ID: faf81b43bfce
Revises: 
Create Date: 2026-08-02 20:08:57.990129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf81b43bfce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piscinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=False),
    sa.Column('profundidad', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_inicio_ciclo', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("estado IN ('activa', 'inactiva', 'mantenimiento')", name='ck_piscinas_estado'),
    sa.CheckConstraint('area_m2 > 0', name='ck_piscinas_area_positiva'),
    sa.CheckConstraint('profundidad > 0', name='ck_piscinas_profundidad_positiva'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('permisos', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("estado IN ('activo', 'inactivo')", name='ck_roles_estado'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_rol')
    )
    op.create_table('cosechas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_piscina', sa.Integer(), nullable=False),
    sa.Column('fecha_cosecha', sa.Date(), nullable=False),
    sa.Column('biomasa_kg', sa.Float(), nullable=False),
    sa.Column('talla_promedio', sa.Float(), nullable=True),
    sa.Column('rendimiento', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('biomasa_kg > 0', name='ck_cosechas_biomasa_positiva'),
    sa.CheckConstraint('talla_promedio > 0 OR talla_promedio IS NULL', name='ck_cosechas_talla_positiva'),
    sa.ForeignKeyConstraint(['id_piscina'], ['piscinas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_piscina', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_instalacion', sa.Date(), nullable=True),
    sa.Column('unidad_medida', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("estado IN ('activo', 'inactivo', 'fallo')", name='ck_sensores_estado'),
    sa.CheckConstraint("tipo IN ('ph', 'oxigeno_disuelto', 'temperatura')", name='ck_sensores_tipo'),
    sa.ForeignKeyConstraint(['id_piscina'], ['piscinas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensores_piscina_tipo', 'sensores', ['id_piscina', 'tipo'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("estado IN ('activo', 'inactivo', 'suspendido')", name='ck_usuarios_estado'),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('lecturas_sensores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sensor', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('estado_validacion', sa.String(length=20), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("estado_validacion IN ('pendiente', 'valida', 'invalida')", name='ck_lecturas_estado_validacion'),
    sa.ForeignKeyConstraint(['id_sensor'], ['sensores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lecturas_fecha_hora', 'lecturas_sensores', ['fecha_hora'], unique=False)
    op.create_index('ix_lecturas_id_sensor', 'lecturas_sensores', ['id_sensor'], unique=False)
    op.create_index('ix_lecturas_sensor_fecha', 'lecturas_sensores', ['id_sensor', 'fecha_hora'], unique=False)
    op.create_table('recomendaciones_alimentacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_piscina', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('cantidad_kg', sa.Float(), nullable=False),
    sa.Column('frecuencia', sa.String(length=50), nullable=False),
    sa.Column('criterio', sa.Text(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("estado IN ('pendiente', 'aplicada', 'rechazada')", name='ck_recomendaciones_estado'),
    sa.CheckConstraint('cantidad_kg > 0', name='ck_recomendaciones_cantidad_positiva'),
    sa.ForeignKeyConstraint(['id_piscina'], ['piscinas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reportes_gerenciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_reporte', sa.String(length=50), nullable=False),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fin', sa.Date(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("tipo_reporte IN ('rendimiento', 'alertas', 'alimentacion')", name='ck_reportes_tipo'),
    sa.CheckConstraint('periodo_fin >= periodo_inicio', name='ck_reportes_periodo_valido'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_lectura', sa.Integer(), nullable=True),
    sa.Column('id_sensor', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('tipo_alerta', sa.String(length=50), nullable=False),
    sa.Column('severidad', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("estado IN ('activa', 'atendida', 'cerrada')", name='ck_alertas_estado'),
    sa.CheckConstraint("severidad IN ('baja', 'media', 'alta', 'critica')", name='ck_alertas_severidad'),
    sa.ForeignKeyConstraint(['id_lectura'], ['lecturas_sensores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_sensor'], ['sensores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alertas_estado', 'alertas', ['estado'], unique=False)
    op.create_index('ix_alertas_fecha_generacion', 'alertas', ['fecha_generacion'], unique=False)
    op.create_table('acciones_correctivas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_alerta', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_accion', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("estado IN ('pendiente', 'en_progreso', 'completada')", name='ck_acciones_estado'),
    sa.ForeignKeyConstraint(['id_alerta'], ['alertas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acciones_correctivas')
    op.drop_index('ix_alertas_fecha_generacion', table_name='alertas')
    op.drop_index('ix_alertas_estado', table_name='alertas')
    op.drop_table('alertas')
    op.drop_table('reportes_gerenciales')
    op.drop_table('recomendaciones_alimentacion')
    op.drop_index('ix_lecturas_sensor_fecha', table_name='lecturas_sensores')
    op.drop_index('ix_lecturas_id_sensor', table_name='lecturas_sensores')
    op.drop_index('ix_lecturas_fecha_hora', table_name='lecturas_sensores')
    op.drop_table('lecturas_sensores')
    op.drop_table('usuarios')
    op.drop_index('ix_sensores_piscina_tipo', table_name='sensores')
    op.drop_table('sensores')
    op.drop_table('cosechas')
    op.drop_table('roles')
    op.drop_table('piscinas')
    # ### end Alembic commands ###
